linters:
  enable:
    - errcheck
    - goconst
    - revive
    - gosec
    - govet
    - ineffassign
    - lll
    - gosimple
    - staticcheck
    - misspell
    - nakedret
    - unconvert
    - unused
  enable-all: false
linters-settings:
  lll:
    line-length: 250
issues:
  exclude-files:
    - schema.go
    - pulumiManifest.go
run:
  timeout: 10m
