---
version: 2
archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
builds:
  - binary: external-dns-provider-adguard
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
      - arm
    goos:
      - darwin
      - windows
      - linux
    goarm:
      - "7"
    ldflags:
      - -X 'main.Version={{ .Tag }}'
      - -X 'main.Gitsha={{ .ShortCommit }}'
    main: ./cmd/webhook
source:
  enabled: true
signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --yes
      - "--bundle=${signature}"
      - "${artifact}"
    artifacts: all
    output: true
sboms:
  - artifacts: archive
  - id: source
    artifacts: source
dockers_v2:
  - images:
      - ghcr.io/muhlba91/external-dns-provider-adguard
    tags:
      - latest
      - "{{ .Env.CI_COMMIT_TAG }}"
      - "{{ .Env.CI_COMMIT_SHA }}"
    build_args:
      CI_COMMIT_TIMESTAMP: "{{ .Env.CI_COMMIT_TIMESTAMP }}"
      CI_COMMIT_SHA: "{{ .Env.CI_COMMIT_SHA }}"
      CI_COMMIT_TAG: "{{ .Env.CI_COMMIT_TAG }}"
    flags:
      - --pull
changelog:
  disable: true
release:
  disable: false
  prerelease: auto
snapshot:
  version_template: "{{ .Tag }}-SNAPSHOT"
